import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Sparkles, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { PageShell } from "@/components/page-shell";
import { EmptyState, Widget } from "@/components/widget";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { listTodayBriefs } from "@/lib/ai/brain.functions";
import { regenerateBriefs } from "@/lib/ai/brain.admin.functions";

export const Route = createFileRoute("/_authenticated/daily-brief")({
  head: () => ({
    meta: [
      { title: "Daily Brief — Trendy Naija" },
      { name: "description", content: "Today's AI-generated Nigeria and Imo State briefs across every category." },
    ],
  }),
  component: DailyBriefPage,
});

function DailyBriefPage() {
  const qc = useQueryClient();
  const listFn = useServerFn(listTodayBriefs);
  const regenFn = useServerFn(regenerateBriefs);
  const briefs = useQuery({ queryKey: ["daily-briefs-today"], queryFn: () => listFn() });
  const regen = useMutation({
    mutationFn: () => regenFn({ data: {} }),
    onSuccess: (r) => {
      toast.success("Briefs regenerated", { description: `${r.generated} generated · ${r.skipped} skipped` });
      qc.invalidateQueries({ queryKey: ["daily-briefs-today"] });
    },
    onError: (e: Error) => toast.error("Regeneration failed", { description: e.message }),
  });

  return (
    <PageShell
      title="Daily Brief"
      description="Grounded AI summaries of what's happening today across Nigeria and Imo State."
      actions={
        <Button size="sm" variant="outline" onClick={() => regen.mutate()} disabled={regen.isPending}>
          <RefreshCw className={`w-3.5 h-3.5 mr-1.5 ${regen.isPending ? "animate-spin" : ""}`} />
          Regenerate
        </Button>
      }
    >
      {briefs.data && briefs.data.length > 0 ? (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
          {briefs.data.map((b) => (
            <Widget
              key={b.id}
              title={b.title}
              subtitle={`${b.scope}${b.category ? ` · ${b.category}` : ""}`}
            >
              <p className="text-sm leading-relaxed">{b.summary}</p>
              {b.sections?.length > 0 && (
                <div className="mt-4 space-y-3">
                  {b.sections.map((s, i) => (
                    <div key={i}>
                      <div className="text-xs font-semibold text-primary">{s.heading}</div>
                      <div className="text-xs text-muted-foreground mt-0.5 leading-relaxed">{s.body}</div>
                    </div>
                  ))}
                </div>
              )}
              {b.top_topics?.length > 0 && (
                <div className="mt-4 flex flex-wrap gap-1.5">
                  {b.top_topics.map((t) => (
                    <Badge key={t} variant="secondary" className="text-[10px]">{t}</Badge>
                  ))}
                </div>
              )}
              {b.model && (
                <div className="mt-3 text-[10px] text-muted-foreground/70">Generated by {b.model}</div>
              )}
            </Widget>
          ))}
        </div>
      ) : (
        <Widget title="Today's brief">
          <EmptyState
            icon={<Sparkles className="w-5 h-5 text-muted-foreground" />}
            title="No brief for today yet"
            description="Click Regenerate to build today's Nigeria + Imo + category briefs from live data."
          />
        </Widget>
      )}
    </PageShell>
  );
}
