/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrendingRouteImport } from './routes/_authenticated/trending'
import { Route as AuthenticatedTopicsRouteImport } from './routes/_authenticated/topics'
import { Route as AuthenticatedStatesRouteImport } from './routes/_authenticated/states'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProviderHealthRouteImport } from './routes/_authenticated/provider-health'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedHashtagsRouteImport } from './routes/_authenticated/hashtags'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyBriefRouteImport } from './routes/_authenticated/daily-brief'
import { Route as AuthenticatedAiInsightsRouteImport } from './routes/_authenticated/ai-insights'
import { Route as AuthenticatedTopicsSlugRouteImport } from './routes/_authenticated/topics.$slug'
import { Route as AuthenticatedNewsIdRouteImport } from './routes/_authenticated/news.$id'
import { Route as ApiPublicHooksTrendsIngestRouteImport } from './routes/api/public/hooks/trends-ingest'
import { Route as ApiPublicHooksSocialIngestRouteImport } from './routes/api/public/hooks/social-ingest'
import { Route as ApiPublicHooksIngestRouteImport } from './routes/api/public/hooks/ingest'
import { Route as ApiPublicHooksAiBrainRouteImport } from './routes/api/public/hooks/ai-brain'
import { Route as AuthenticatedNewsClusterIdRouteImport } from './routes/_authenticated/news.cluster.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrendingRoute = AuthenticatedTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopicsRoute = AuthenticatedTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatesRoute = AuthenticatedStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProviderHealthRoute =
  AuthenticatedProviderHealthRouteImport.update({
    id: '/provider-health',
    path: '/provider-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHashtagsRoute = AuthenticatedHashtagsRouteImport.update({
  id: '/hashtags',
  path: '/hashtags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyBriefRoute = AuthenticatedDailyBriefRouteImport.update({
  id: '/daily-brief',
  path: '/daily-brief',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiInsightsRoute = AuthenticatedAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopicsSlugRoute = AuthenticatedTopicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedTopicsRoute,
} as any)
const AuthenticatedNewsIdRoute = AuthenticatedNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedNewsRoute,
} as any)
const ApiPublicHooksTrendsIngestRoute =
  ApiPublicHooksTrendsIngestRouteImport.update({
    id: '/api/public/hooks/trends-ingest',
    path: '/api/public/hooks/trends-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSocialIngestRoute =
  ApiPublicHooksSocialIngestRouteImport.update({
    id: '/api/public/hooks/social-ingest',
    path: '/api/public/hooks/social-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIngestRoute = ApiPublicHooksIngestRouteImport.update({
  id: '/api/public/hooks/ingest',
  path: '/api/public/hooks/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAiBrainRoute = ApiPublicHooksAiBrainRouteImport.update({
  id: '/api/public/hooks/ai-brain',
  path: '/api/public/hooks/ai-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewsClusterIdRoute =
  AuthenticatedNewsClusterIdRouteImport.update({
    id: '/cluster/$id',
    path: '/cluster/$id',
    getParentRoute: () => AuthenticatedNewsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/daily-brief': typeof AuthenticatedDailyBriefRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hashtags': typeof AuthenticatedHashtagsRoute
  '/news': typeof AuthenticatedNewsRouteWithChildren
  '/provider-health': typeof AuthenticatedProviderHealthRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/states': typeof AuthenticatedStatesRoute
  '/topics': typeof AuthenticatedTopicsRouteWithChildren
  '/trending': typeof AuthenticatedTrendingRoute
  '/news/$id': typeof AuthenticatedNewsIdRoute
  '/topics/$slug': typeof AuthenticatedTopicsSlugRoute
  '/news/cluster/$id': typeof AuthenticatedNewsClusterIdRoute
  '/api/public/hooks/ai-brain': typeof ApiPublicHooksAiBrainRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
  '/api/public/hooks/social-ingest': typeof ApiPublicHooksSocialIngestRoute
  '/api/public/hooks/trends-ingest': typeof ApiPublicHooksTrendsIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/daily-brief': typeof AuthenticatedDailyBriefRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hashtags': typeof AuthenticatedHashtagsRoute
  '/news': typeof AuthenticatedNewsRouteWithChildren
  '/provider-health': typeof AuthenticatedProviderHealthRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/states': typeof AuthenticatedStatesRoute
  '/topics': typeof AuthenticatedTopicsRouteWithChildren
  '/trending': typeof AuthenticatedTrendingRoute
  '/news/$id': typeof AuthenticatedNewsIdRoute
  '/topics/$slug': typeof AuthenticatedTopicsSlugRoute
  '/news/cluster/$id': typeof AuthenticatedNewsClusterIdRoute
  '/api/public/hooks/ai-brain': typeof ApiPublicHooksAiBrainRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
  '/api/public/hooks/social-ingest': typeof ApiPublicHooksSocialIngestRoute
  '/api/public/hooks/trends-ingest': typeof ApiPublicHooksTrendsIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/_authenticated/daily-brief': typeof AuthenticatedDailyBriefRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hashtags': typeof AuthenticatedHashtagsRoute
  '/_authenticated/news': typeof AuthenticatedNewsRouteWithChildren
  '/_authenticated/provider-health': typeof AuthenticatedProviderHealthRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/states': typeof AuthenticatedStatesRoute
  '/_authenticated/topics': typeof AuthenticatedTopicsRouteWithChildren
  '/_authenticated/trending': typeof AuthenticatedTrendingRoute
  '/_authenticated/news/$id': typeof AuthenticatedNewsIdRoute
  '/_authenticated/topics/$slug': typeof AuthenticatedTopicsSlugRoute
  '/_authenticated/news/cluster/$id': typeof AuthenticatedNewsClusterIdRoute
  '/api/public/hooks/ai-brain': typeof ApiPublicHooksAiBrainRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
  '/api/public/hooks/social-ingest': typeof ApiPublicHooksSocialIngestRoute
  '/api/public/hooks/trends-ingest': typeof ApiPublicHooksTrendsIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-insights'
    | '/daily-brief'
    | '/dashboard'
    | '/hashtags'
    | '/news'
    | '/provider-health'
    | '/settings'
    | '/states'
    | '/topics'
    | '/trending'
    | '/news/$id'
    | '/topics/$slug'
    | '/news/cluster/$id'
    | '/api/public/hooks/ai-brain'
    | '/api/public/hooks/ingest'
    | '/api/public/hooks/social-ingest'
    | '/api/public/hooks/trends-ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-insights'
    | '/daily-brief'
    | '/dashboard'
    | '/hashtags'
    | '/news'
    | '/provider-health'
    | '/settings'
    | '/states'
    | '/topics'
    | '/trending'
    | '/news/$id'
    | '/topics/$slug'
    | '/news/cluster/$id'
    | '/api/public/hooks/ai-brain'
    | '/api/public/hooks/ingest'
    | '/api/public/hooks/social-ingest'
    | '/api/public/hooks/trends-ingest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-insights'
    | '/_authenticated/daily-brief'
    | '/_authenticated/dashboard'
    | '/_authenticated/hashtags'
    | '/_authenticated/news'
    | '/_authenticated/provider-health'
    | '/_authenticated/settings'
    | '/_authenticated/states'
    | '/_authenticated/topics'
    | '/_authenticated/trending'
    | '/_authenticated/news/$id'
    | '/_authenticated/topics/$slug'
    | '/_authenticated/news/cluster/$id'
    | '/api/public/hooks/ai-brain'
    | '/api/public/hooks/ingest'
    | '/api/public/hooks/social-ingest'
    | '/api/public/hooks/trends-ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksAiBrainRoute: typeof ApiPublicHooksAiBrainRoute
  ApiPublicHooksIngestRoute: typeof ApiPublicHooksIngestRoute
  ApiPublicHooksSocialIngestRoute: typeof ApiPublicHooksSocialIngestRoute
  ApiPublicHooksTrendsIngestRoute: typeof ApiPublicHooksTrendsIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trending': {
      id: '/_authenticated/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof AuthenticatedTrendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topics': {
      id: '/_authenticated/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof AuthenticatedTopicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/states': {
      id: '/_authenticated/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof AuthenticatedStatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider-health': {
      id: '/_authenticated/provider-health'
      path: '/provider-health'
      fullPath: '/provider-health'
      preLoaderRoute: typeof AuthenticatedProviderHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hashtags': {
      id: '/_authenticated/hashtags'
      path: '/hashtags'
      fullPath: '/hashtags'
      preLoaderRoute: typeof AuthenticatedHashtagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-brief': {
      id: '/_authenticated/daily-brief'
      path: '/daily-brief'
      fullPath: '/daily-brief'
      preLoaderRoute: typeof AuthenticatedDailyBriefRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-insights': {
      id: '/_authenticated/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AuthenticatedAiInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topics/$slug': {
      id: '/_authenticated/topics/$slug'
      path: '/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof AuthenticatedTopicsSlugRouteImport
      parentRoute: typeof AuthenticatedTopicsRoute
    }
    '/_authenticated/news/$id': {
      id: '/_authenticated/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof AuthenticatedNewsIdRouteImport
      parentRoute: typeof AuthenticatedNewsRoute
    }
    '/api/public/hooks/trends-ingest': {
      id: '/api/public/hooks/trends-ingest'
      path: '/api/public/hooks/trends-ingest'
      fullPath: '/api/public/hooks/trends-ingest'
      preLoaderRoute: typeof ApiPublicHooksTrendsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/social-ingest': {
      id: '/api/public/hooks/social-ingest'
      path: '/api/public/hooks/social-ingest'
      fullPath: '/api/public/hooks/social-ingest'
      preLoaderRoute: typeof ApiPublicHooksSocialIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest': {
      id: '/api/public/hooks/ingest'
      path: '/api/public/hooks/ingest'
      fullPath: '/api/public/hooks/ingest'
      preLoaderRoute: typeof ApiPublicHooksIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ai-brain': {
      id: '/api/public/hooks/ai-brain'
      path: '/api/public/hooks/ai-brain'
      fullPath: '/api/public/hooks/ai-brain'
      preLoaderRoute: typeof ApiPublicHooksAiBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/news/cluster/$id': {
      id: '/_authenticated/news/cluster/$id'
      path: '/cluster/$id'
      fullPath: '/news/cluster/$id'
      preLoaderRoute: typeof AuthenticatedNewsClusterIdRouteImport
      parentRoute: typeof AuthenticatedNewsRoute
    }
  }
}

interface AuthenticatedNewsRouteChildren {
  AuthenticatedNewsIdRoute: typeof AuthenticatedNewsIdRoute
  AuthenticatedNewsClusterIdRoute: typeof AuthenticatedNewsClusterIdRoute
}

const AuthenticatedNewsRouteChildren: AuthenticatedNewsRouteChildren = {
  AuthenticatedNewsIdRoute: AuthenticatedNewsIdRoute,
  AuthenticatedNewsClusterIdRoute: AuthenticatedNewsClusterIdRoute,
}

const AuthenticatedNewsRouteWithChildren =
  AuthenticatedNewsRoute._addFileChildren(AuthenticatedNewsRouteChildren)

interface AuthenticatedTopicsRouteChildren {
  AuthenticatedTopicsSlugRoute: typeof AuthenticatedTopicsSlugRoute
}

const AuthenticatedTopicsRouteChildren: AuthenticatedTopicsRouteChildren = {
  AuthenticatedTopicsSlugRoute: AuthenticatedTopicsSlugRoute,
}

const AuthenticatedTopicsRouteWithChildren =
  AuthenticatedTopicsRoute._addFileChildren(AuthenticatedTopicsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiInsightsRoute: typeof AuthenticatedAiInsightsRoute
  AuthenticatedDailyBriefRoute: typeof AuthenticatedDailyBriefRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHashtagsRoute: typeof AuthenticatedHashtagsRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRouteWithChildren
  AuthenticatedProviderHealthRoute: typeof AuthenticatedProviderHealthRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatesRoute: typeof AuthenticatedStatesRoute
  AuthenticatedTopicsRoute: typeof AuthenticatedTopicsRouteWithChildren
  AuthenticatedTrendingRoute: typeof AuthenticatedTrendingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiInsightsRoute: AuthenticatedAiInsightsRoute,
  AuthenticatedDailyBriefRoute: AuthenticatedDailyBriefRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHashtagsRoute: AuthenticatedHashtagsRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRouteWithChildren,
  AuthenticatedProviderHealthRoute: AuthenticatedProviderHealthRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatesRoute: AuthenticatedStatesRoute,
  AuthenticatedTopicsRoute: AuthenticatedTopicsRouteWithChildren,
  AuthenticatedTrendingRoute: AuthenticatedTrendingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksAiBrainRoute: ApiPublicHooksAiBrainRoute,
  ApiPublicHooksIngestRoute: ApiPublicHooksIngestRoute,
  ApiPublicHooksSocialIngestRoute: ApiPublicHooksSocialIngestRoute,
  ApiPublicHooksTrendsIngestRoute: ApiPublicHooksTrendsIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
