/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrendingRouteImport } from './routes/_authenticated/trending'
import { Route as AuthenticatedTopicsRouteImport } from './routes/_authenticated/topics'
import { Route as AuthenticatedStatesRouteImport } from './routes/_authenticated/states'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProviderHealthRouteImport } from './routes/_authenticated/provider-health'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedHashtagsRouteImport } from './routes/_authenticated/hashtags'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiInsightsRouteImport } from './routes/_authenticated/ai-insights'
import { Route as ApiPublicHooksIngestRouteImport } from './routes/api/public/hooks/ingest'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrendingRoute = AuthenticatedTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopicsRoute = AuthenticatedTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatesRoute = AuthenticatedStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProviderHealthRoute =
  AuthenticatedProviderHealthRouteImport.update({
    id: '/provider-health',
    path: '/provider-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHashtagsRoute = AuthenticatedHashtagsRouteImport.update({
  id: '/hashtags',
  path: '/hashtags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiInsightsRoute = AuthenticatedAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksIngestRoute = ApiPublicHooksIngestRouteImport.update({
  id: '/api/public/hooks/ingest',
  path: '/api/public/hooks/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hashtags': typeof AuthenticatedHashtagsRoute
  '/news': typeof AuthenticatedNewsRoute
  '/provider-health': typeof AuthenticatedProviderHealthRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/states': typeof AuthenticatedStatesRoute
  '/topics': typeof AuthenticatedTopicsRoute
  '/trending': typeof AuthenticatedTrendingRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hashtags': typeof AuthenticatedHashtagsRoute
  '/news': typeof AuthenticatedNewsRoute
  '/provider-health': typeof AuthenticatedProviderHealthRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/states': typeof AuthenticatedStatesRoute
  '/topics': typeof AuthenticatedTopicsRoute
  '/trending': typeof AuthenticatedTrendingRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hashtags': typeof AuthenticatedHashtagsRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/provider-health': typeof AuthenticatedProviderHealthRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/states': typeof AuthenticatedStatesRoute
  '/_authenticated/topics': typeof AuthenticatedTopicsRoute
  '/_authenticated/trending': typeof AuthenticatedTrendingRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-insights'
    | '/dashboard'
    | '/hashtags'
    | '/news'
    | '/provider-health'
    | '/settings'
    | '/states'
    | '/topics'
    | '/trending'
    | '/api/public/hooks/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-insights'
    | '/dashboard'
    | '/hashtags'
    | '/news'
    | '/provider-health'
    | '/settings'
    | '/states'
    | '/topics'
    | '/trending'
    | '/api/public/hooks/ingest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-insights'
    | '/_authenticated/dashboard'
    | '/_authenticated/hashtags'
    | '/_authenticated/news'
    | '/_authenticated/provider-health'
    | '/_authenticated/settings'
    | '/_authenticated/states'
    | '/_authenticated/topics'
    | '/_authenticated/trending'
    | '/api/public/hooks/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksIngestRoute: typeof ApiPublicHooksIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trending': {
      id: '/_authenticated/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof AuthenticatedTrendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topics': {
      id: '/_authenticated/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof AuthenticatedTopicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/states': {
      id: '/_authenticated/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof AuthenticatedStatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider-health': {
      id: '/_authenticated/provider-health'
      path: '/provider-health'
      fullPath: '/provider-health'
      preLoaderRoute: typeof AuthenticatedProviderHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hashtags': {
      id: '/_authenticated/hashtags'
      path: '/hashtags'
      fullPath: '/hashtags'
      preLoaderRoute: typeof AuthenticatedHashtagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-insights': {
      id: '/_authenticated/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AuthenticatedAiInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/ingest': {
      id: '/api/public/hooks/ingest'
      path: '/api/public/hooks/ingest'
      fullPath: '/api/public/hooks/ingest'
      preLoaderRoute: typeof ApiPublicHooksIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiInsightsRoute: typeof AuthenticatedAiInsightsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHashtagsRoute: typeof AuthenticatedHashtagsRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedProviderHealthRoute: typeof AuthenticatedProviderHealthRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatesRoute: typeof AuthenticatedStatesRoute
  AuthenticatedTopicsRoute: typeof AuthenticatedTopicsRoute
  AuthenticatedTrendingRoute: typeof AuthenticatedTrendingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiInsightsRoute: AuthenticatedAiInsightsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHashtagsRoute: AuthenticatedHashtagsRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedProviderHealthRoute: AuthenticatedProviderHealthRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatesRoute: AuthenticatedStatesRoute,
  AuthenticatedTopicsRoute: AuthenticatedTopicsRoute,
  AuthenticatedTrendingRoute: AuthenticatedTrendingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksIngestRoute: ApiPublicHooksIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
